
<#import "parts/common.ftlh" as c>

<@c.page>
<head>
        <title>Webapp</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css"
        rel="stylesheet">
</head>

<body>
<div insert="~{header :: header}"></div>
<div class="container my-3">
    <H1 align="center">Hello, this is ILearning – Task 3</H1>
    <H3 align="center"> <a href="/main">Sign in</a></H3>
</div>
</body>
</@c.page>